name: analyze

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 6 * * 1"

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  analyze:
    runs-on: 'ubuntu-22.04'

    steps:
      - name: Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get -y install xfonts-75dpi xfonts-base
          curl --silent --show-error --location --max-redirs 3 --fail --retry 3 --output wkhtmltopdf-linux-amd64.deb https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
          sudo dpkg -i wkhtmltopdf-linux-amd64.deb
          sudo ldconfig
          rm wkhtmltopdf-linux-amd64.deb

      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: go
          queries: security-and-quality

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v3
