name: lint

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    strategy:
      matrix:
        go: ['1.21']
        os: ['ubuntu-22.04']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Prerequisites
      run: |
        sudo apt-get update
        sudo apt-get -y install xfonts-75dpi xfonts-base
        curl --silent --show-error --location --max-redirs 3 --fail --retry 3 --output wkhtmltopdf-linux-amd64.deb https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
        sudo dpkg -i wkhtmltopdf-linux-amd64.deb
        sudo ldconfig
        rm wkhtmltopdf-linux-amd64.deb

    - name: Prepare checkout
      run: git config --global core.autocrlf false

    - name: Checkout
      uses: actions/checkout@v4

    - name: Lint
      uses: golangci/golangci-lint-action@v6.5.2
      with:
        version: "v1.54"
        args: --timeout=5m
