name: tests

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        go: ['1.21']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Prerequisites
      run: |
        sudo apt-get update
        sudo apt-get -y install xfonts-75dpi xfonts-base
        curl --silent --show-error --location --max-redirs 3 --fail --retry 3 --output wkhtmltopdf-linux-amd64.deb https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
        sudo dpkg -i wkhtmltopdf-linux-amd64.deb
        sudo ldconfig
        rm wkhtmltopdf-linux-amd64.deb

    - name: Prepare checkout
      run: git config --global core.autocrlf false

    - name: Checkout
      uses: actions/checkout@v4

    - name: Test
      run: go test -v -coverprofile coverage.txt -covermode atomic ./...

    - name: Coverage
      uses: codecov/codecov-action@v5
